### ISSUE TITLE
waypoints Not working

### ISSUE THREAD

**Issue by Markiie** [Indyuce/mmocore#17]
Afternoon,

Noticed then when I do /waypoints or /waypoint nothing happens. No GUI, no error and no console error.  Absolutely nothing happens when performing this command.

**Comment by Flirtey** [comment]
Hey Markiie, I'm one of the admins for the MMOCore team. Super sorry for the late reply, we don't get much activity here so we don't check it too often. We are much more active in our support discord over with mythicmobs.

The issue here is citizens. Citizens has a /waypoints command that completely overrides MMOCore. The best way of fixing this since citizens won't change it, is to go into mmocore commands.yml and changing the command. We promise it works <3
